name: R2 ETL Agenda
on:
  schedule:
      - cron: '21 6 * * *'
  workflow_dispatch:
jobs:
  run-pipeline:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        repository: marlonmoreira1/sturdy-fishstick
        token: ${{ secrets.MY_PRIVATE_TOKEN }}
        path: pv
      
    - name: create-json
      id: create-json
      uses: jsdaniell/create-json@1.1.2
      with:
        name: "credentials.json"
        json: ${{ secrets.STORAGE_KEY }}
        
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r pv/requirements.txt
        
    - name: Run R2 Etl agenda
      env:
        STORAGE_KEY: ${{ secrets.STORAGE_KEY }}        
        API_KEY: ${{ secrets.API_KEY }}
        GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
        R2_URL: ${{ secrets.R2_URL }}
        ACCESS_KEY_R2: ${{ secrets.ACCESS_KEY_R2 }}
        SECRET_KEY_R2: ${{ secrets.SECRET_KEY_R2 }}
        
      run: |
        python pv/live_r2_etl.py
